image: alpine:latest

pages:
  stage: deploy
  before_script:
    - apk add git hugo
  script:
    - mkdir -p extra
    - git clone --depth 1 'https://github.com/CherryMan/tetris.git' extra/tetris
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master
