image: alpine:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  before_script:
    - apk add hugo
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master
