image: alpine:latest

pages:
  stage: deploy
  before_script:
    - apk add git rsync
  script:
    - git clone --depth 1 'https://github.com/CherryMan/tetris.git' tetris
    - mkdir public
    - rsync -av --exclude '.*' --exclude '/public' . 'public'
  artifacts:
    paths:
      - public
  only:
    - master
