baseURL = "https://cherryman.org"
languageCode = "en-us"
title = "CherryMan"
theme = "papermod"
mainsections = ["posts"]

[params]
env = "production"
defaultTheme = "auto"

[params.profileMode]
enabled = false

[params.homeInfoParams]
Title = "Hello!"
Content = """
Not much to see here yet.
"""

[[params.socialIcons]]
name = "github"
title = "github"
url = "https://github.com/cherryman"

[[params.socialIcons]]
name = "twitter"
title = "twitter"
url = "https://twitter.com/sheryparv"
